// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Constructores;

import java.io.PrintStream;

/************************************************************/
/**
 * 
 */
public class Memorias extends Catalogo {
	/**
	 * 
	 */
	private String Resumen;
	/**
	 * 
	 */
	private String Abstract;
	/**
	 * 
	 */
	private String conferenciaPresentada;

    public Memorias(String titulo, String fechaIngreso, String Autor,String Resumen,String Abstract,String conferenciaPresentada,String Estado) {
        super(titulo, fechaIngreso, Autor,Estado);
        this.Resumen=Resumen;
        this.Abstract=Abstract;
        this.conferenciaPresentada=conferenciaPresentada;
    }
    public void Agregar(Memorias memoria) {
		// TODO Auto-generated method stub
	 PrintStream ps = getPrintStream("Memorias.txt");

        ps.println(memoria.getTitulo() + ";" + memoria.getFechaIngreso()+ ";" + memoria.getAutor()+ ";" + memoria.getResumen() + ";" + memoria.getAbstract()+";"+memoria.getConferenciaPresentada()+";"+memoria.getEstado());
	}
 

    public String getResumen() {
        return Resumen;
    }

    public void setResumen(String Resumen) {
        this.Resumen = Resumen;
    }

    public String getAbstract() {
        return Abstract;
    }

    public void setAbstract(String Abstract) {
        this.Abstract = Abstract;
    }

    public String getConferenciaPresentada() {
        return conferenciaPresentada;
    }

    public void setConferenciaPresentada(String conferenciaPresentada) {
        this.conferenciaPresentada = conferenciaPresentada;
    }
};
