// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Constructores;

import java.io.PrintStream;

/************************************************************/
/**
 * 
 */
public class Revistas extends Catalogo {
	/**
	 * 
	 */
	private String codigoISSN;
	/**
	 * 
	 */
	private String edicion;

    public Revistas(String titulo, String fechaIngreso, String Autor,String codigoISSN,String edicion,String Estado) {
        super(titulo, fechaIngreso, Autor,Estado);
        this.codigoISSN=codigoISSN;
        this.edicion=edicion;
    }
    public void Agregar(Revistas revistas) {
		// TODO Auto-generated method stub
	 PrintStream ps = getPrintStream("Revistas.txt");

        ps.println(revistas.getTitulo() + ";" + revistas.getFechaIngreso()+ ";" + revistas.getAutor()+ ";" + revistas.getCodigoISSN() + ";" + revistas.getEdicion()+";"+revistas.getEstado());
	}
    

    public String getCodigoISSN() {
        return codigoISSN;
    }

    public void setCodigoISSN(String codigoISSN) {
        this.codigoISSN = codigoISSN;
    }

    public String getEdicion() {
        return edicion;
    }

    public void setEdicion(String edicion) {
        this.edicion = edicion;
    }
};
