// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Constructores;

import java.io.PrintStream;

/************************************************************/
/**
 * 
 */
public class Tesis extends Catalogo {
	/**
	 * 
	 */
	private String Resumen;
	/**
	 * 
	 */
	private String Abstract;

    public Tesis(String titulo, String fechaIngreso, String Autor,String Resumen,String Abstract,String Estado) {
        super(titulo, fechaIngreso, Autor,Estado);
        this.Resumen=Resumen;
        this.Abstract=Abstract;
    }
     public void Agregar(Tesis tesis) {
		// TODO Auto-generated method stub
	 PrintStream ps = getPrintStream("Tesis.txt");

        ps.println(tesis.getTitulo() + ";" + tesis.getFechaIngreso()+ ";" + tesis.getAutor()+ ";" + tesis.getResumen() + ";" + tesis.getAbstract()+";"+tesis.getEstado());
	}
   

    public String getResumen() {
        return Resumen;
    }

    public void setResumen(String Resumen) {
        this.Resumen = Resumen;
    }

    public String getAbstract() {
        return Abstract;
    }

    public void setAbstract(String Abstract) {
        this.Abstract = Abstract;
    }
};
